### ISSUE TITLE
Table widget panics on rendering cell when not enough room provided

### ISSUE THREAD

**Issue by sadovsf** [ratatui-org/ratatui#474]
Hi, iam working on small open source project and i did run into panic when i use table with not enough room for all columns.
https://github.com/sadovsf/RadioLog

## Description
Binary panics on not enough room to render cell.

## To Reproduce
Just compile linked project, open small terminal window and run it. Area for table that it fails on as i look at it is currently:
```rs
Rect {
    x: 10,
    y: 2,
    width: 30,
    height: 12
}
```

## Expected behavior
Cell should not be rendered or as more expensive solution, ellipse on text should be rendered. For sure it should not panic.

## Environment
- OS: MacOS Ventura 13.5.1
- Terminal Emulator: iTerm but same happens in vscode and native terminal app so should not matter
- Backend: crossterm

## Additional context
Call stack:
```txt
thread 'main' panicked at 'Trying to access position outside the buffer: x=80, y=2, area=Rect { x: 0, y: 0, width: 80, height: 25 }', /Users/sadovsf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.22.0/src/buffer.rs:238:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: ratatui::buffer::Buffer::index_of
             at /Users/sadovsf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.22.0/src/buffer.rs:238:9
   3: ratatui::buffer::Buffer::get_mut
             at /Users/sadovsf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.22.0/src/buffer.rs:205:17
   4: ratatui::buffer::Buffer::set_style
             at /Users/sadovsf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.22.0/src/buffer.rs:399:17
   5: ratatui::widgets::table::render_cell
             at /Users/sadovsf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.22.0/src/widgets/table.rs:526:5
   6: <ratatui::widgets::table::Table as ratatui::widgets::StatefulWidget>::render
             at /Users/sadovsf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.22.0/src/widgets/table.rs:453:17
   7: ratatui::terminal::Frame<B>::render_stateful_widget
             at /Users/sadovsf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.22.0/src/terminal.rs:123:9
   8: <radio_log::ui::log_table::LogTable as radio_log::traits::ui_element::UIElement>::render
             at ./src/ui/log_table.rs:93:9
   9: radio_log::traits::ui_element::UIElement::on_draw
             at ./src/traits/ui_element.rs:57:9
  10: radio_log::ui_handler::UIHandler::draw_single
             at ./src/ui_handler.rs:96:9
  11: radio_log::app::App::draw_app
             at ./src/app.rs:121:9
  12: radio_log::app::App::run::{{closure}}
             at ./src/app.rs:54:37
  13: ratatui::terminal::Terminal<B>::draw
             at /Users/sadovsf/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.22.0/src/terminal.rs:279:9
  14: radio_log::app::App::run
             at ./src/app.rs:53:13
  15: radio_log::main
             at ./src/main.rs:58:18
  16: core::ops::function::FnOnce::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
```

Local variables state in Statefull widget render for Table:
![image](https://github.com/ratatui-org/ratatui/assets/2211533/8dc7019b-03fa-4f16-9600-b158edc2f4c8)

**Comment by orhun** [comment]
I can't reproduce this with `ratatui` `0.23.0`. Also, it seems like you're using `0.22.0`.

 Can you maybe provide a simpler reproducible example with the latest version of `ratatui`?

**Comment by sadovsf** [comment]
I'am sorry i did not realized iam using older version (facepalm). Seems fixed in 0.23.0
