### ISSUE TITLE
Improve `Buffer` `Debug` impl for unit testing.

### ISSUE THREAD

**Issue by joshka** [ratatui-org/ratatui#603]
## Problem
Right now a lot of the unit testing in Ratatui and Ratatui apps / libs uses the TestBackend. This leads to fairly verbose tests and is often a few steps to setup. An alternative is to just use the buffer and call assert_buffer_eq! on two buffers. For simple text only buffers this is sufficient, but it breaks down a little when we have to deal with styled text as the setup has to individually style the cells / areas. E.g.: https://github.com/ratatui-org/ratatui/blob/9f371000968044e09545d66068c4ed4ea4b35d8a/src/widgets/block.rs#L1136-L1145

When this fails, the output of the test is overly verbose, which makes finding the specific failure a manual inspection, and doesn't give the code that would help fix the test if it was wrong.
<details><summary>Test failure output</summary>

```
Executing task: cargo test --package ratatui --lib --all-features -- widgets::block::tests::title_border_style --exact --nocapture 

   Compiling ratatui v0.24.0 (/Users/joshka/local/ratatui)
    Finished test [unoptimized + debuginfo] target(s) in 1.52s
     Running unittests src/lib.rs (target/debug/deps/ratatui-ae7ef03207775e1c)

running 1 test
thread 'widgets::block::tests::title_border_style' panicked at src/widgets/block.rs:1144:9:
buffer contents not equal
expected: Buffer {
    area: Rect { x: 0, y: 0, width: 15, height: 3 },
    content: [
        "┌test─────────┐",
        "│             │",
        "└─────────────┘",
    ],
    styles: [
        x: 0, y: 0, fg: Blue, bg: Reset, underline: Reset, modifier: NONE,
        x: 1, y: 1, fg: Reset, bg: Reset, underline: Reset, modifier: NONE,
        x: 14, y: 1, fg: Blue, bg: Reset, underline: Reset, modifier: NONE,
    ]
}
actual: Buffer {
    area: Rect { x: 0, y: 0, width: 15, height: 3 },
    content: [
        "┌test─────────┐",
        "│             │",
        "└─────────────┘",
    ],
    styles: [
        x: 0, y: 0, fg: Yellow, bg: Reset, underline: Reset, modifier: NONE,
        x: 1, y: 1, fg: Reset, bg: Reset, underline: Reset, modifier: NONE,
        x: 14, y: 1, fg: Yellow, bg: Reset, underline: Reset, modifier: NONE,
    ]
}
diff:
0: at (0, 0)
  expected: Cell { symbol: "┌", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "┌", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

1: at (1, 0)
  expected: Cell { symbol: "t", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "t", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

2: at (2, 0)
  expected: Cell { symbol: "e", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "e", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

3: at (3, 0)
  expected: Cell { symbol: "s", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "s", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

4: at (4, 0)
  expected: Cell { symbol: "t", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "t", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

5: at (5, 0)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

6: at (6, 0)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

7: at (7, 0)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

8: at (8, 0)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

9: at (9, 0)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

10: at (10, 0)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

11: at (11, 0)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

12: at (12, 0)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

13: at (13, 0)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

14: at (14, 0)
  expected: Cell { symbol: "┐", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "┐", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

15: at (0, 1)
  expected: Cell { symbol: "│", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "│", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

16: at (14, 1)
  expected: Cell { symbol: "│", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "│", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

17: at (0, 2)
  expected: Cell { symbol: "└", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "└", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

18: at (1, 2)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

19: at (2, 2)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

20: at (3, 2)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

21: at (4, 2)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

22: at (5, 2)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

23: at (6, 2)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

24: at (7, 2)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

25: at (8, 2)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

26: at (9, 2)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

27: at (10, 2)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

28: at (11, 2)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

29: at (12, 2)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

30: at (13, 2)
  expected: Cell { symbol: "─", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "─", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

31: at (14, 2)
  expected: Cell { symbol: "┘", fg: Blue, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }
  actual:   Cell { symbol: "┘", fg: Yellow, bg: Reset, underline_color: Reset, modifier: NONE, skip: false }

stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: ratatui::widgets::block::tests::title_border_style
             at ./src/widgets/block.rs:1144:9
   3: ratatui::widgets::block::tests::title_border_style::{{closure}}
             at ./src/widgets/block.rs:1128:29
   4: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test widgets::block::tests::title_border_style ... FAILED

failures:

failures:
    widgets::block::tests::title_border_style

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 369 filtered out; finished in 0.02s
```

</details>

It would be nice to instead just write something like:
```rust
let expected = Buffer::with_lines(...).with_styles(...);
assert_eq!(buf, expected);
```
And have the output show the buffer in the same format so it can be directly copied into a failing test or compared using e.g. the [pretty-assertions crate](https://crates.io/crates/pretty-assertions).

## Solution
It would be nice to have a debug format that round trips into the test for representing styled buffers. We have this for the buffer text, but not for the cell styles. Something like:
```rust
vec![
    Line::from(Span::styled("┌test─────────┐", Style::new().yellow())),
    Line::from(vec![
        Span::styled("│", Style::new().yellow(),
        Span::raw("             "),
        Span::styled("│", Style::new().yellow()))
    ]),
    Line::from(Span::styled("└─────────────┘", Style::new().yellow())),
]
```

## Alternatives
1. It's possible that https://github.com/ratatui-org/ratatui/issues/493 might help this significantly as we'd be able to represent each buffer line as a more shorthand string.
2. We could keep the existing macro approach and add styles + ranges to the end of the macro (this neglects the opportunity to use pretty-assertions though.
3. Should this be `Buffer::to_lines()`? (this approach doesn't seem like it will lead to a compact assertion output)

## Additional context
- https://github.com/ratatui-org/ratatui/pull/453
- https://github.com/ratatui-org/ratatui/discussions/78

There are a lot of places where we need to write characterization tests for widgets that exist already to ensure that when we change a particular behavior we maintain or know when we implement breaking changes. This happens both in Ratatui code as well as other libraries that use widgets. This should support both a test first and a test after development flow (as both as useful). The solution should:
1. Keep test code succinct / minimal
2. Make test output compact / useful in quickly finding errors
4. Make it easy to copy validated correct test output to tests to produce succeeding tests from failing tests

**Comment by 47-dev** [comment]
it seems like a thoughtful improvement to enhance the testing experience
